platform :ios, '7.0'

target 'EXPMatchers+OCMockTests', :exclusive => true do
  pod 'OCMock', '~> 2.2.2'
  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => "v0.3.0.beta1"
  pod 'Expecta+OCMock', :path => "../"
end
